### ISSUE TITLE
ADJUST plugin "constant vector to EM.m" -bug

### ISSUE THREAD

**Issue by jutako** [bwrc/ctap#19] opened 2018-01-11 08:37 UTC
branch: dev
pipeline: runctap_manu2_basic.m

The problem is that ctapeeg_ADJUST.m gets non-epoched data which causes num_epoch = 1 which further results in a constant vector of ones to be passed on to EM.m which crashes because variance of the input data is zero. EM is supposed to optimize something but there is nothing to optimize in a constant vector.

Problem 1: Why the data is not epoched although clearly epoched data is expected?
Problem 2: ADJUST does nothing to safeguard against this bug.

If Ben is unable to reproduce Jussi will look into this at some point.

Error message:
Error using  / 
Matrix dimensions must agree.
Error in EM>Bayes (line 181)
    prob=((1/(sqrt(2*pi*var)))*exp((-1)*((point-med)^2)/(2*var)));
Error in EM (line 121)
        prior1_i=[prior1_i
                prior1_old*Bayes(med1_old,var1_old,vec(i))/...
Error in ctapeeg_ADJUST (line 189)
    thr_V = EM(nuovaV);
Error in ctapeeg_detect_bad_comps (line 168)
        [bad_comp_match, horiz, verti, blink, disco] =
        ctapeeg_ADJUST(EEG...
Error in CTAP_detect_bad_comps (line 77)
        [EEG, params, result] = ctapeeg_detect_bad_comps(EEG, Arg);
Error in CTAP_pipeline_looper/sbf_execute_pipefun (line 357)
            [i_EEG, i_Cfg_tmp] = Cfg.pipe.stepSets(i).funH{k}(i_EEG,
            Cfg);
Error in CTAP_pipeline_looper (line 209)
                i_Cfg_tmp = sbf_execute_pipefun;
Error in runctap_manu2_basic_jkor (line 88)
    CTAP_pipeline_looper(Cfg,...

**Comment by zenBen** [comment] 2018-01-11 09:17
Looking at the code I have, the function Bayes is defined thus:
```
function prob=Bayes(med, var, point)
    if var == 0
        prob=1;
    else
        prob=((1/(sqrt(2*pi*var)))*exp((-1)*((point-med)^2)/(2*var)));
    end
```

This *should* clearly safeguard against variance == 0

I will try to reproduce now.

**Comment by zenBen** [comment] 2018-01-11 10:30
Having run past the stated problem, I find that line 181 gives me NaN, not error. The arguments to Bayes are `Bayes(med = NaN, var = NaN, point = 1)`
Perhaps this is due to different versions of Matlab. All the symptoms leading to the problem seem to be the same.
Anyhow it seems clear this function shouldn't be called if epochs = 1.
Not sure if other features of ADJUST can be reliably computed for continuous data, but their entire approach depends on removing what they call 'gross artefacts', which are 
> non-stereotyped artifacts due to movements of the electrodes on the scalp arising from large muscle movements or external sources

(quoting the ADJUST tutorial from their website). Leading to the recommended pipeline:

> • filter the data;
> • remove gross artifacts (defined as epochs in which the EEG signal overcomes the voltage threshold of 150 V in more than 33% of the channels)
> • perform ICA;
> • run ADJUST.

In the context of CTAP, this is quite a significant implication, since it changes the whole way that we do things, forcing epoching before ICA and preventing a continuous analysis.

An alternative approach might be to just regularly epoch the data before `ctapeegADJUST()` is called, ignoring the 'gross artefacts', and allow users to proceed at their own discretion.

**Comment by zenBen** [comment] 2018-01-11 10:45
For the moment, I have guarded against the bug by editing `ctapeegADJUST()` at line 200 as follows:

```
    if num_epoch > 1
        thr_V = EM(nuovaV);
    else
        thr_V = 0;
    end
```

Thus, instead of just calling `EM()` with a constant vector `nuovaV`, we set `thr_V = 0`. So in later tests for the ADJUST features, e.g.
`horiz = (SED >= thr_SED) & (med_L.*med_R < 0) & (nuovaV >= thr_V);`
The nuovaV comparisons will be all true, which preserves the logical value of the rest of the statement (by AND, if I got it right).

**Comment by zenBen** [comment] 2018-01-11 10:47
I also cleaned up the rest of the function a bit but that is just cosmetic

**Comment by zenBen** [comment] 2018-01-11 13:06
Finally, I also added option to epoch continuous data (using `ctapeeg_epoch_data()` with 1sec regular epoching), when calling the ADJUST option in `ctapeeg_detect_bad_comps`

So if calling ADJUST, use the argument `detect_bad_comps.epoch = true` to epoch data before passing to `ctapeegADJUST` (will only do so if data is continuous).

Closing now.

**Closed by zenBen** 2018-01-11 13:06 UTC
Labels: help wanted
